# Authors:
#   Sebastian Birke <git@se-bi.de>
#   Unai Martinez-Corral
#
# Copyright 2019-2021 Unai Martinez-Corral <unai.martinezcorral@ehu.eus>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: 'impl'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ impl ]

env:
  DOCKER_BUILDKIT: 1

jobs:


  impl-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian/buster
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: ./utils/setup.sh

    - run: >-
        dockerPull -c ${{ matrix.os }}
        ghdl/yosys
        pkg/ghdl-yosys-plugin
        pkg/yosys

    - run: >-
        dockerBuild -c ${{ matrix.os }} -d
        build/impl

    - name: Login to container registries
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: ./utils/registry-login
      with:
        cmd: |
          echo '${{ secrets.GCR_JSON_KEY }}' | docker login gcr.io -u _json_key --password-stdin
          echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
          echo '${{ secrets.DOCKER_PASS }}' | docker login docker.io -u '${{ secrets.DOCKER_USER }}' --password-stdin

    - if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      run: >-
        dockerPush ${{ matrix.os }}
        build/impl


  impl-prjs:
    needs: [ impl-build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os:
          - debian/buster
        task:
          - { arch: ice40, prj: icestorm   }
          - { arch: ecp5,  prj: prjtrellis }
    name: '[${{ matrix.os }}] impl · ${{ matrix.task.arch }} ${{ matrix.task.prj }}'
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: ./utils/setup.sh

    - run: >-
        dockerPull -c ${{ matrix.os }}
        build/impl
        pkg/nextpnr/${{ matrix.task.arch }}
        pkg/${{ matrix.task.prj }}

    - run: >-
        dockerBuild -c ${{ matrix.os }} -d
        impl/${{ matrix.task.arch }}
        impl/${{ matrix.task.prj }}

    - run: dockerTest ${{ matrix.os }} impl/${{ matrix.task.arch }}
    - run: dockerTest ${{ matrix.os }} impl/${{ matrix.task.prj  }}

    - name: Login to container registries
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: ./utils/registry-login
      with:
        cmd: |
          echo '${{ secrets.GCR_JSON_KEY }}' | docker login gcr.io -u _json_key --password-stdin
          echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
          echo '${{ secrets.DOCKER_PASS }}' | docker login docker.io -u '${{ secrets.DOCKER_USER }}' --password-stdin

    - if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      run: >-
        dockerPush ${{ matrix.os }}
        impl/${{ matrix.task.arch }}
        impl/${{ matrix.task.prj }}


  impl:
    needs: [ impl-build, impl-prjs ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian/buster
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: ./utils/setup.sh

    - run: >-
        dockerPull -c ${{ matrix.os }}
        build/impl
        pkg/nextpnr/ice40
        pkg/nextpnr/ecp5
        pkg/nextpnr/generic
        pkg/icestorm
        pkg/prjtrellis

    - run: >-
        dockerBuild -c ${{ matrix.os }} -d
        impl/generic
        impl/pnr
        impl

    - run: dockerTest ${{ matrix.os }} impl/generic
    - run: dockerTest ${{ matrix.os }} impl/pnr
    - run: dockerTest ${{ matrix.os }} impl

    - name: Login to container registries
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: ./utils/registry-login
      with:
        cmd: |
          echo '${{ secrets.GCR_JSON_KEY }}' | docker login gcr.io -u _json_key --password-stdin
          echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
          echo '${{ secrets.DOCKER_PASS }}' | docker login docker.io -u '${{ secrets.DOCKER_USER }}' --password-stdin

    - if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      run: >-
        dockerPush ${{ matrix.os }}
        impl/generic
        impl/pnr
        impl
